### ISSUE TITLE
Can't handle any CSV file with end of line at end of last line

### ISSUE THREAD

**Issue by mbevin** [bahmutov/csv-load-sync#7]
It reads the following empty last line as empty string, and then asserts as it doesn't have the expected number of columns.

**Comment by bahmutov** [comment]
if you can submit a PR with failing test and a fix I will merge it in quickly

**Comment by mbevin** [comment]
Unless my understanding is wrong, any file with a blank line at the end would constitute a failing test, and adding this check (e.g. after the similar if( !line) check) would fix it:

    if (!line.trim().length) {
        return;
    }

**Comment by bahmutov** [comment]
Just checked, seems to work fine
